### ISSUE TITLE
[db] Tracker

### ISSUE THREAD

**Issue by at15** [at15/go.ice#8]
- [ ] query builder, it's not a good idea to manually build the string
  - [ ] I remember I saw a database driver or some sort that do SQL prepare in go instead leave it to the protocol and claim this is much faster ...
- [ ] orm, may not need it .. since there isn't much business logic in code using go.ice (benchbub for now)
- [ ] https://github.com/golang/go/issues/20268 found it while looking at go-sqlite issues, it seems `sql.Open` is not the only way to open a connection, and which go version supports this

**Comment by at15** [comment]
actually I think I just need to support pg and sqlite for now ... and use raw SQL ... only need to consider problem of drivers if we want to write benchmark frameworks for relational databases ...

**Comment by at15** [comment]
for the database config and manager etc. design, it might worth looking at some java framework for inspiration, i.e. http://www.mybatis.org/mybatis-3/configuration.html
